from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional, Union


@dataclass
class Prompt:
    """
    A single prompt from the evaluation suite.

    Prompt input is JSONL-only. Each line must provide `prompt_id` and `prompt`.
    """

    prompt_id: str
    prompt: str
    tier: Optional[str] = None
    family: Optional[str] = None
    language: Optional[str] = None
    tags: List[str] = field(default_factory=list)
    contract: Optional[Dict[str, Any]] = None
    prompt_file: Optional[str] = None
    prompt_file_stem: Optional[str] = None

    @property
    def prompt_text(self) -> str:
        """Backward-compatible alias for the prompt body."""
        return self.prompt


@dataclass
class LLMResponse:
    """
    A single generated code sample from an LLM (or file fixture).

    Field names match the on-disk JSONL schema (see data/generations_mvp.jsonl)
    so responses can be constructed with LLMResponse(**record).
    """

    prompt_id: str
    sample_id: Union[str, int]
    model: str
    code: str
    pip_installs: List[str] = field(default_factory=list)
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class CodeSample:
    """A generated code sample paired with its originating prompt and stage output."""

    prompt_id: str
    prompt_source: str
    response: LLMResponse
    stage_results: List[Dict[str, Any]] = field(default_factory=list)
    prompt_family: Optional[str] = None
    prompt_contract: Optional[Dict[str, Any]] = None
    artifact_metadata: Dict[str, Any] = field(default_factory=dict)
    artifact_file: Optional[str] = None
    prompt_file: Optional[str] = None
    prompt_file_stem: Optional[str] = None
    run_id: Optional[int] = None
    warnings: List[Dict[str, Any]] = field(default_factory=list)
    failure_report: Optional[Dict[str, Any]] = None

    @property
    def code(self) -> str:
        """The raw code generated by the LLM. Read by every validation stage."""
        return self.response.code

    @property
    def sample_id(self) -> Union[str, int]:
        return self.response.sample_id

    @property
    def model(self) -> str:
        return self.response.model


class FindingType(str, Enum):
    """
    Operational Hallucinated Artifact (OHA) taxonomy.

    Aligns with the categories enumerated in README.md and the research
    methodology notes: each value names a deterministically-verifiable
    failure class where the generated code references a fabricated or
    incorrect external entity.
    """

    NONEXISTENT_PACKAGE = "nonexistent_package"
    VERSION_NOT_FOUND = "version_not_found"
    NONEXISTENT_ATTRIBUTE = "nonexistent_attribute"
    INVALID_API_USAGE = "invalid_api_usage"
    CLI_NOT_FOUND = "cli_not_found"
    INVALID_FLAG = "invalid_flag"
    INVALID_DOMAIN = "invalid_domain"
    DEAD_ENDPOINT = "dead_endpoint"
    RUNTIME_REFERENCE_ERROR = "runtime_reference_error"


@dataclass
class Finding:
    """A single OHA finding emitted by a validation stage."""

    prompt_id: str
    sample_id: Union[str, int]
    type: FindingType
    details: str
    severity: int = 0


@dataclass
class PipelineConfig:
    """
    Configuration for the hallucination validation pipeline.
    """

    suite_path: Path
    output_dir: Path
    model: str
    samples_per_prompt: int = 1
    runs_per_prompt: Optional[int] = None
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    reasoning_effort: Optional[str] = None
    retries: int = 3
    request_timeout: float = 60.0
    gateway_base_url: Optional[str] = None
    gateway_model_override: Optional[str] = None
    gateway_model_map_path: Optional[Path] = None
    skip_dynamic: bool = False
    skip_urls: bool = False
    save_code: bool = False
    save_raw_output: bool = False
    run_failure_checks: bool = False
    results_dir: Optional[Path] = None
    evaluate_artifacts: Optional[Path] = None
    disable_sandbox: bool = False
    recurrence_threshold: int = 2
    fail_on_generation_error: bool = False
    write_global_summary: bool = False

    @property
    def store_artifacts(self) -> bool:
        """Backward-compatible alias for legacy callers."""
        return self.save_code

    @property
    def effective_runs_per_prompt(self) -> int:
        """Canonical repeat count; keeps samples_per_prompt backward-compatible."""
        return self.runs_per_prompt if self.runs_per_prompt is not None else self.samples_per_prompt
